### ISSUE TITLE
[Definition en cours] : Analyser la littératie en automatique

### ISSUE THREAD

**Issue by etienneCharignon** [betagouv/competences-pro-serveur#152]
Capacité à communiquer par écrit de manière compréhensible (porte sur les faits et le vocabulaire adapté)
Le texte est compréhensible à la première lecture: 100%
Le texte est compréhensible après plusieurs lectures: 50%
Le texte est difficilement compréhensible: 10%

Évaluation du niveau de détail d’explication (jour, heure, zone, encombrement escabeau)
Le texte comporte 3 détails ou plus: 100%
Le texte comporte deux détails : 75%
Le texte comporte 1 détail: 40%
Le texte ne comporte aucun détail: 10%

Evaluation du niveau de syntaxe et d’orthographe
Le texte comporte moins de 3 fautes: 100%
Le texte comporte entre 3 et 5 fautes: 75%
Le texte comporte entre 5 et 8 fautes: 40%
Le texte comporte plus de 8 fautes: 10%
le premier me semble difficile à coder, mais les autres pas
on peut en parler avec ceux que ça intéresse :clin_d'œil:

**Comment by francois2metz** [comment]
Rien de prévu la dessus pour le moment, surtout avec la réflexion sur le nouveau module illettrisme.
