### ISSUE TITLE
Sécurisation de l'API

### ISSUE THREAD

**Issue by etienneCharignon** [betagouv/competences-pro-serveur#163]
A partir du moment ou l'on va remonter les compétences fortes dans l'écran de fin, Il nous faut protéger plus fortement l'accès aux sessions d'évaluation coté client.

Plusieurs pistes possibles : 

- token d'authentification
- générer un uuid d'évaluation.

**Comment by shanser** [comment]
les uid sont fait dans #164 
Est-ce qu'on fait le token en plus ?

**Comment by shanser** [comment]
après discussion, nous pensons que pour le moment, l'uuid suffit et que si on a besoin d'aller plus loin, on le fera dans une issue à part
