### ISSUE TITLE
Afficher "les compétences les plus fortes" dans le PDF de restitution

### ISSUE THREAD

**Issue by morissetcl** [betagouv/competences-pro-serveur#207]
Avec leur description +  icône

![Capture d’écran 2019-11-05 à 18 29 25](https://user-images.githubusercontent.com/20596535/68230857-381f6800-fffa-11e9-8cb3-b965ee036bc8.png)

**Comment by GaelleOttan** [comment]
suite à la question de françois auj dans le slack (est ce qu'on veut faire qqc là dessus?) je confirme que côté métier on aimerait toujours les jauges (mais pas besoin des boutons des métiers associés qui ont été normalement remplacés par etienne par du texte et des liens)
