### ISSUE TITLE
Supprimer l'efficience pour la restitution bureau

### ISSUE THREAD

**Issue by francois2metz** [betagouv/competences-pro-serveur#211]
Ne pas l'afficher dans la partie haute et ne pas la prendre en compte dans l'efficience globale

**Comment by morissetcl** [comment]
Vue en équipe: issue en pause le temps d'avoir une définition plus précise de que l'on souhaite pour l'efficience globale.

**Comment by shanser** [comment]
ce qu'on veut pour l'efficience globale :

- l'efficience globale est la moyenne des efficiences sauf le bureau
- si une situation n'a pas d'efficience ( pour cause d'abandon par exemple ) elle est ignorée de la moyenne

**Comment by shanser** [comment]
message d'Alexis sur Slack: 

> renommer l'efficience globale en "Potentiel global EVA* **" en mentionnant des asterix en légendes pour préciser
> * ne tient pas compte la situation bureau qui doit être analysée seule
> ** le potentiel global ne tient pas compte des situations quittées pendant l’exercice
