### ISSUE TITLE
Calculer Z pour les restitutions

### ISSUE THREAD

**Issue by francois2metz** [betagouv/competences-pro-serveur#267]
Z = (valeur de l'évalué·e - moyenne glissante) / ecart type glissant

https://en.wikipedia.org/wiki/Standard_score

**Comment by etienneCharignon** [comment]
J'ai un plantage dans le cas ou l'écart type est à 0. Ce n'est pas un drame puisque ce n'est pas un cas qui devrait arriver (il faudrait que tout le monde est exactement le même résultat ou qu'il n'y ai qu'une seule évaluation). On pourrait malgré tout se protéger en metant nil dans Z dans le cas ou l'écart type est à zero.
