### ISSUE TITLE
Problème d'affichage du détails d'un événement

### ISSUE THREAD

**Issue by morissetcl** [betagouv/competences-pro-serveur#75]
<img width="1408" alt="Capture d’écran 2019-06-05 à 12 22 49" src="https://user-images.githubusercontent.com/20596535/58949687-4dfbd900-878d-11e9-96c0-5cb04230f4c1.png">

**Comment by francois2metz** [comment]
t'aurais un lien ?

**Comment by morissetcl** [comment]
> t'aurais un lien ?

Celui la par exemple, mais j'ai ce souci sur tout les événements.
https://api.competences-pro.beta.gouv.fr/admin/evenements/19249
