### ISSUE TITLE
Revoir le calcul de l'efficience

### ISSUE THREAD

**Issue by francois2metz** [betagouv/competences-pro-serveur#80]
- [x] Efficience par situation: mettre indéterminé si une des compétences (hors compréhension et persévérance) est indéterminé
- [x] Efficience globale: mettre indéterminé si une des situation a un niveau indéterminé

**Comment by francois2metz** [comment]
J'ai commencé le premier point dans la branche *rapport/evaluation*.

**Comment by morissetcl** [comment]
J'ai commencé le second point, ça m'intéresserai de voir ça avec toi à ton retour.
